export * from './IASection'
// export * from './IAHero'
export * from './IAServices/IAServices'
export * from './IAProjects/IAProjects'
export * from './IAAbout/IAAbout'
export * from './IAConnection/IAConnection'
export * from './IAContacts/IAContacts'