version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:80"
      - "3000:443"
    environment:
      NODE_ENV: development
